### ISSUE TITLE
WebCam not working

### ISSUE THREAD

**Issue by fred-head** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#10]
Hi,

the webcam isn't working, do you have some hints to fix it?

**Comment by 5T33Z0** [comment]
The integrated camera is working fine over here using macOS Catalina. Make sure it's enabled in the BIOS and perform an NVRAM Reset.

**Comment by fred-head** [comment]
Thanks fpr your help. In the end i had to generate a USBPorts.kext with Hackintool. With this kext webcam is working.

**Comment by 5T33Z0** [comment]
Ok. Glad to hear it's working now. Although generating a USBPorts.kext should be unnecessary since this Notebook only has 2 UBS 3 Ports and one USB 2 and then maybe another internal port for Bluetooth so it should stay well within Apples 15 port limit.
