### ISSUE TITLE
DeviceProperties for 1366x768 px on Monterey

### ISSUE THREAD

**Issue by Jan-E** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#11]
First of all: thanks for sharing your EFI.

I tried this on a Lenovo X230 tablet and ran into a problem with my 1366x768 LCD. Half way during the booting it seemed to stuck at the Apple logo and the progress bar at about 50%. With a fresh install of Monterey beta 4 there was an indication that it got further than that: the system started talking about voice activation.

Installing Big Sur and importing from a TimeMachine backup went fine, but after upgrading to Monterey the same thing happened: seemingly stuck during booting. I was in luck that screen sharing was already activated in Big Sur and that it still worked after the upgrade. So I could still use the system with any VNC client!

I went to Settings > Display and found this:
![x230-monterey](https://user-images.githubusercontent.com/1757825/128177514-c5844e3a-0dfc-48f1-8671-dc7fe9e3ea93.png)

Screen resolution was set at 1280x1080, which my 1366x768 display could not handle. Choosing 'Default for display' or 1024x768 did not help either. After some trial and error I found the culprit: the device_type in the DeviceProperties was set to VGA compatible controller. Removing #device_type made my system boot like it should.

Please remove ot disable the device_type in '#PciRoot(0x0)/Pci(0x2,0x0) 1366x768 px'.

**Comment by Jan-E** [comment]
Somewhat related question: can you adjust the screen brightness on your test system(s)? I could not get it to work yet. Any clue would be appreciated.

**Comment by 5T33Z0** [comment]
Thanks for your feedback. I will look into it. Installing Monterey requires special preparations. Read the "Monterey Instructions.md" contained in the Zip. Brightness controls probably don't work for you because the X230 requires different renames for the brightness keys.

For the X230 try this EFI instead: https://github.com/banhbaoxamlan/X230-Hackintosh.

**Comment by Jan-E** [comment]
I tried the other repo as well. In fact that one gave me the idea to remove the VGA compatible device_type. But no brightness settings with that repo either, despite regenerating the SSDT-PM.aml

**Comment by 5T33Z0** [comment]
SSDT-PM has nothing to with Brightness Control. SSDT-PNFL is for Brightnes and Q13, Q14, etc renames are for the buttons.
