### ISSUE TITLE
can't complete the installation  of Monterey

### ISSUE THREAD

**Issue by writinggreenz** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#14]
I tried to install Monterey on my T530 using usb boot directly, but failed.
Then I use the config.plist of Monterey within the EFI to start Big Sur, then in the Big Sur, I install Monterey on other disk.
Then my computer restart several times, almost completed the installation.
But at the end of the installation the voice of apple's conductor can be heard, the screen  still displayed the logo of apple.
Then I added "-v" in the config.plist.
The picture shows below.
![883775830](https://user-images.githubusercontent.com/37840835/134337879-0bea6b8b-668d-4dc1-9fda-8a7bc2758adb.jpg)

**Comment by 5T33Z0** [comment]
You cannot install Monterey directly on the machine. Follow `Monterey_Instructions.md` included in the EFI download.

**Comment by Jan-E** [comment]
What is the resolution of your LCD panel? If it is 1366x768 remove ot disable the `device_type: VGA compatible controller` in 'PciRoot(0x0)/Pci(0x2,0x0) 1366x768 px'. See https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/issues/11 

Just a tip: activate 'screen sharing' before updating a Big Sur installation. Screen sharing still works after the update, even when the LCD panel cannot display anything.

**Comment by 5T33Z0** [comment]
@Jan-E So, then you finish the install remotely by connecting to the machine over ethernet?

**Comment by Jan-E** [comment]
Yes, that is what I did. Only afterwards I discovered that I had to remove `device_type: VGA compatible controller` in 'PciRoot(0x0)/Pci(0x2,0x0) 1366x768 px'.

**Comment by 5T33Z0** [comment]
Okay, I will remove that key in the next update. Are you 100 % sure that this caused your display not working?

**Comment by Jan-E** [comment]
> Okay, I will remove that key in the next update. Are you 100 % sure that this caused your display not working?

Yes

**Comment by writinggreenz** [comment]
@5T33Z0 Thank you, I understand. Without patching graphics, the computer can not start normally. I need another computer that can run Monterey to patch this disk. Am I right?

**Comment by 5T33Z0** [comment]
Says so in the instructions. It's supposed to be possible with OpenCore Legacy Patcher as well, but I don't know how.

**Comment by writinggreenz** [comment]
@5T33Z0 Thank you.

**Comment by Jan-E** [comment]
> @5T33Z0 Thank you, I understand. Without patching graphics, the computer can not start normally. I need another computer that can run Monterey to patch this disk. Am I right?

The computer can start OK without patching the graphics. There only is no hardware acceleration. no brightness control and video memory is only 4 MB. See https://github.com/banhbaoxamlan/X230-Hackintosh/issues/73#issuecomment-919306857 

Be sure to remove `device_type: VGA compatible controller` in 'PciRoot(0x0)/Pci(0x2,0x0) 1366x768 px'.

**Comment by 5T33Z0** [comment]
@Jan-E But you don't even know which panel his model is using… On the HD+ panel this is not an issue.

**Comment by Jan-E** [comment]
I assumed @writinggreenz has a 1366x768 panel, because only hearing the the voice of apple's conductor was exactly what I experienced in https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/issues/11#issue-960353088

**Comment by 5T33Z0** [comment]
I experienced that too when I fist installed Monterey. But that was because the system booted into the installation dialog but the display didn't turn on because of the missing drivers.

**Comment by Jan-E** [comment]
OK. Yet another case when the LCD could nog handle the video output.

**Comment by writinggreenz** [comment]
@Jan-E My panel is 1080p

**Comment by Jan-E** [comment]
> @Jan-E My panel is 1080p

O, well try to finish the installation using scheen sharing and a VNC client.

**Comment by 5T33Z0** [comment]
I just tested the screen sharing from my desktop which runs big sur. Didn't even have to use a VCN client. Trying to update to Monterey beta 7 next.

**Comment by writinggreenz** [comment]
@5T33Z0 @Jan-E Thank you.

**Comment by 5T33Z0** [comment]
Screensharing is working:
![Bildschirmfoto 2021-09-22 um 16 02 26](https://user-images.githubusercontent.com/76865553/134358586-d643db0a-211b-44b9-a602-40c4e56db840.png)

**Comment by Jan-E** [comment]
Did you succeed in updating to beta 7? I am running into installer errors. There are more reports about this: https://twitter.com/classicii_mrmac?lang=en

**Comment by 5T33Z0** [comment]
Nope. Installer crashes for me on Both desktop and Laptop

Then I tried downloading the standalone installer, bit that's broken as well (as reported)

![Bildschirmfoto 2021-09-23 um 09 04 53](https://user-images.githubusercontent.com/76865553/134469718-94ccb9ba-549b-4477-9e61-1d20199fbd7b.png)

**Comment by Jan-E** [comment]
Strange thing: in a VM I succeeded with a 2.36 GB (IIRC) delta update.

**Comment by 5T33Z0** [comment]
With this workaround I got the full installer working on the desktop:

https://www.insanelymac.com/forum/topic/348725-pre-release-macos-monterey/?do=findComment&comment=2767298

**Comment by Jan-E** [comment]
> I experienced that too when I fist installed Monterey. But that was because the system booted into the installation dialog but the display didn't turn on because of the missing drivers.

Maybe that is the same problem after all. `VGA compatible controller` refers to a 4:3 screen. 1600x900 or HD+ panel is 16:9. Try remming out the \#device_type.

Thanks for the tip about the beta 7 workaround.

**Comment by 5T33Z0** [comment]
Well but if it can display 16:9 it sure can display 4:3, I guess.  But I'll give it a try later since I have a working installer now.

**Comment by Jan-E** [comment]
In my case it could not display 1366x768 (16:9), only 1280x1024 (5:4) and 1024x768 (4:3).
See the screenshot, made using screen sharing: https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/issues/11#issue-960353088

**Comment by 5T33Z0** [comment]
Okay, I will comment-out the entries in both Framebuffer Patches

**Comment by 5T33Z0** [comment]
The new EFI will be releases once 074 is released officially. 

And: no more extra config for Monterey will be necessary. Only 2 or 3 settings have to be changes to adjust it to the macOS of your choise:

- Framebuffer-Patch
- SystemProductName
- csr-active-config

**Comment by 5T33Z0** [comment]
Weird: The install was going through pretty smoothly. The display even stayed on. But during the setup the installer asked my to turn on FileVault which I didn't wanted. But I could not cancel it, I only coul go "back". So I did an then I got a spinning wheel of death. And after wards I couldn't get back in the Installer. this beta 7 is horrible.

**Comment by Jan-E** [comment]
Pheww. I am glad I did not try it and concentrated on releasing my B2B apps for iPadOS 15.0

**Comment by 5T33Z0** [comment]
**SUCCESS!**

- Clean Install beta 7 working
- VESA Mode is working (GUI is super sluggish during the first time setup - especially the time zone window since it's animated)
-  Everything working fine once the HD4000 Patch is applied

Proof:
![Bildschirmfoto 2021-09-24 um 15 55 40](https://user-images.githubusercontent.com/76865553/134692599-a356d946-15cf-4fab-84fa-f37447fd094f.png)

Will Upload the EFI later this day.

**Comment by Jan-E** [comment]
Top! When I have got the time I will follow this script:
https://www.insanelymac.com/forum/topic/348725-pre-release-macos-monterey/page/62/?tab=comments#comment-2767386 

No issues with 4:3 vs 16:9 this time?

**Comment by 5T33Z0** [comment]
https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/releases/tag/074.2
