### ISSUE TITLE
Dont see open core options 

### ISSUE THREAD

**Issue by Pyro108** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#15]
[opencore-2021-09-27-194944.txt](https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/files/7240284/opencore-2021-09-27-194944.txt)im having issues installing big sur have the same cpu and wifi card as this guide but dont see any options only a windows drive i set the bios accordingly

**Comment by 5T33Z0** [comment]
Which version of my EFI are you using?
What "Options" are you refering to?
Did you perform a NVRAM reset?
Are you doing a clean install?
Are you using a USB3  Stick?
Did you change the USB Mode accordingly?

**Comment by Pyro108** [comment]
im using EFI version 2.0 latest im doing a clean install using a formated usb stick with rufus following dortania guide when i boot up the usb stick i have no options not even nvram reset all i see is a windows drive 
![1](https://user-images.githubusercontent.com/91510588/135087710-1fcbc167-37d8-400e-81dc-9a4e95147784.jpg)

**Comment by 5T33Z0** [comment]
That's not the latest version I uploaded! The current version doesn't use a custom theme! This is the latest version: 

https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/releases/tag/074.2 

I've tested the exact EFI Folder on a USB Install Stick created in macOS:

![20210928_144256_HDR](https://user-images.githubusercontent.com/76865553/135089937-b9a53897-a7c7-4491-a81f-5302e5e7023d.jpg)

Rufus is primarily for installing Windows and Linux. I don't think this works for creating a macOS boot stick. If the Rufus tutorial is incorrect, report a problem at the [Dortania Bugtracker](https://github.com/dortania/bugtracker/).

**Comment by Pyro108** [comment]
i was using the correct files 0.7.4 V2.0 i added the theme to the config plist i even removed the themes and still wont get any options to install.

**Comment by 5T33Z0** [comment]
As you can see in my picture: the EFI Folder works with USB Installer created in macOS. In other words: my EFI Folder is not the issue. The issue is your installer.

**Comment by Pyro108** [comment]
got it to work i set hide auxiliary to false and got the recovery.dmg and other options in the opencore boot menu to show up. big sur runs smooth everything works good so far it also boots up fast
![20210929_151151](https://user-images.githubusercontent.com/91510588/135516229-7a7fe3a4-2fed-4d56-8073-460de17eef06.jpg)

**Comment by 5T33Z0** [comment]
The only thing you would have needed to do is hit space bar to show them…

**Comment by Pyro108** [comment]
ah ok this is my first time doing this and im learning as i go
