### ISSUE TITLE
Boot halts at "BuildActDeviceEntry exit"

### ISSUE THREAD

**Issue by super-vinnie** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#2]
Hello there, total newbie here. I have the T530 w/ HD+ and i7-3520m, and I have set up my EFI following the instructions closely. Unfortunately, I cannot get it to work at all. I am currently using the DSDT-less config, but I have used the DSDT HD+ config as well to no avail.

Regardless of the configuration, it halts at _**BuildActDeviceEntry exit**_, with Lilu indicating several lines above that it has stopped user patcher on request. I have tried several different fixes, but none have made any difference. I have also tried another EFI (osbaldov/T530-BigSur-EFI), and that has the exact same issue.

I can get it running with a hacked together Clover config, but I'd prefer to use this and have everything work. Plus, OpenCore is supposedly better anyway..

I've attached an image of the point at which it halts.

![halt](https://user-images.githubusercontent.com/81345237/112421959-7bb96580-8d06-11eb-9f53-ed3a482a2745.png)

Here is my EFI folder in its current state: 
[EFI.zip](https://github.com/5T33Z0/Lenovo-T530-Hackinosh-OpenCore/files/6202176/EFI.zip)

Thanks for your time.

**Comment by 5T33Z0** [comment]
Wrong order of Kexts. LILU has to be Number 1. ALWAYS!

Order: LILU, VIRTUALSMC. WHATEVERGREEN… the REST. 

USBINJECTALL is unnecessary. USE XHCI Portlimit Quirk instead (which is also unnecessary since it's a Laptop with only a few USB ports and stays within the 15 Ports Limit)

**Comment by super-vinnie** [comment]
Ah, so it was simply an ordering screw-up. Oddly enough other configurations had the VirtualSMC kext first, so I falsely assumed that it was first and I did not need to change the ordering. The USBInjectAll was leftover from another proposed fix, but it expectedly did nothing to help. Thank you for the help, nobody else gave me a straight answer. Marking as closed.
