### ISSUE TITLE
Broken graphics acceleration on Big Sur 11.4?

### ISSUE THREAD

**Issue by TheForgottenKing** [5T33Z0/Lenovo-T530-Hackinosh-OpenCore#8]
Using the second-newest EFI folder.

Specs are i5-3320M, 8GB, 128GB, and HD 4000 only.

The system boots fine and the About this Mac menu reports 1536MB, but there is no graphics acceleration, animations are slow and there is no transparency. Am I missing something that needs to be changed for Big Sur 11.4?

**Comment by 5T33Z0** [comment]
Use the latest release from today. Catalina is recommended, btw. This notebook does not benefit from running Big Sur at all!

**Comment by TheForgottenKing** [comment]
I prefer the Big Sur UI, so I'll try and give it a go. What changes do I need to csr? I will set SMBIOS to a MacbookPro11,4

**Comment by 5T33Z0** [comment]
1. Read the EFI Install instructions in the repo
2. The config includes the correct csr values for various OSes in vommentes-out entries.
